name: Agile Chicago Style Podcast
favicon: null
layout_spectrum: 0
typography_spectrum: 0.28335
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0086c9'
    - '#addbef'
    - '#42acda'
    - '#88cbe8'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5299220778979361
purpose: []
