name: Agile Chicago Style Podcast
favicon: null
layout_spectrum: 0.77422
typography_spectrum: 0.61787
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0086c9'
    - '#addbef'
    - '#42acda'
    - '#88cbe8'
  brandStrength: 0.6915468946099281
  lightness: 0.7416433736216277
  saturation: 0.14734686445444822
  rhythmicContrast: 0.5299220778979361
purpose: []
