typography_spectrum: 0.05642386257491711
content_rating:
  adult: false
color:
  brandColors:
    - '#ffffff'
    - '#0086c9'
    - '#addbef'
    - '#42acda'
    - '#88cbe8'
  brandStrength: 0.43029663391881573
  lightness: 0.007390777702618501
  saturation: 0.22646374401599537
  rhythmicContrast: 0.44876460932794554
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.05081394051229305
analytics:
  google: null
  facebook: null
  twitter: '@AgileChicago'
author:
  name: 'Rick Waters, Matt Beam'
  email: AgileChicagoStyle@gmail.com
  url: 'http://agilechicagostyle.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d053f0b6-bee7-4294-b84d-3806a19b3c6f.png
name: Agile Chicago Style
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Us
    id: 02f715be-8077-4f88-a828-8a939ccf2002
    type: content
  - name: It Starts With an Invitation
    id: 89d5dd21-d533-4745-9ac2-6c5b827f9c75
    type: content
  - name: Agile Politics - Part 2
    id: 06e62a6a-4bb7-4199-b204-895f21c5904e
    type: content
  - name: Agile Politics - Part 1
    id: 600a57ad-0a9b-4754-9686-3f08f38d74b1
    type: content
  - name: A True Agile Transformation
    id: 9940140a-fe74-4517-8150-ecd2144aa415
    type: content
  - name: 'Being Agile or Doing Agile, with Tom Mellor'
    id: e14cb3f2-d97d-4fa2-8b7e-e9408095780d
    type: content
  - name: 'Talking CSD with Chet Hendrickson, Ron Jeffries and Brian Levy'
    id: c47f0bee-70b0-4133-9574-9360094e366f
    type: content
  - name: What’s Eating Agile?
    id: 4d691cf9-0392-423e-9e94-bbddb1aef486
    type: content
  - name: Introducing… Matt Beam!
    id: 8f46dce0-9782-4c9c-ab06-ea139d888a08
    type: content
  - name: 'The Road to DevOps, with Jack Walser'
    id: dbbfc550-7b19-4564-95c2-1987a1a67a88
    type: content
  - name: Discussing the State of Scrum – with Maria Matarelli and Aakash Srinivasan
    id: 10f6e35b-0c20-4acc-b685-02738df1fa82
    type: content
  - name: 'Agile Training and Coaching, with Aakash Srinivasan'
    id: 4be9e3d4-7fee-45df-b1ae-5d8967adb0ad
    type: content
  - name: 'Agile Potpurri, with Vivek Angiras'
    id: 78463475-3422-4930-b2fe-b8af60e91ed8
    type: content
  - name: '“Don’t Scrum Undone”, with Angela Johnson'
    id: 020709d8-2edc-4d47-a720-aa01d1034fbd
    type: content
  - name: Dave Sharrock – 3 Stages of Scaling Agile Organizations
    id: e45f084d-f100-4a8e-8d63-ecb14cc24ba9
    type: content
  - name: The Agile Life and Times of Mike Marchi
    id: f6c221a4-3d51-4e52-a9d6-9454d1ce9c58
    type: content
  - name: Scrum Discussion with Angela Druckman
    id: 642d26bf-cd06-4272-9315-38308516a499
    type: content
  - name: 'Agile: From Theory into Practice for Social Good'
    id: efba280f-3be0-484e-b28b-eb57a946f10b
    type: content
  - name: Our Guests
    id: c08973be-b1c3-45a8-9a62-b70ed6926eac
    type: content
  - name: The Promise
    id: c9effd8f-7e76-43e4-9360-e7a9621f10b5
    type: content
  - name: Drag
    id: 0da5eb6b-b814-43c7-8d3c-c134bfd041be
    type: content
  - name: 5 ScrumMasters From Hell
    id: 2e38ae01-f857-446b-9c86-08cb3a799b9d
    type: content
favicon: null
title: Agile Chicago Style Podcast
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/b955a224-daea-433f-bd0d-3a355601a1ef.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/b955a224-daea-433f-bd0d-3a355601a1ef.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Helping UNLEASH the Agile Community in Chicago
purpose:
  - type: contact
    url: 'mailto:AgileChicagoStyle@gmail.com'
    label: email us!
