typography_spectrum: 0.7890841016026748
content_rating:
  adult: false
color:
  brandColors:
    - '#ffffff'
    - '#0086c9'
    - '#addbef'
    - '#42acda'
    - '#88cbe8'
  brandStrength: 0.38006261486375686
  lightness: 0.0013794815951571017
  saturation: 0.22762727383367423
  rhythmicContrast: 0.44941170699488703
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.10378518542597569
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Rick Waters
  email: AgileChicagoStyle@gmail.com
  url: 'http://agilechicagostyle.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6d62cf0e-4218-4435-bca9-c19067e24b80.png
name: Agile Chicago Style
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: A True Agile Transformation
    id: 9940140a-fe74-4517-8150-ecd2144aa415
    type: content
  - name: 'Being Agile or Doing Agile, with Tom Mellor'
    id: e14cb3f2-d97d-4fa2-8b7e-e9408095780d
    type: content
  - name: 'Talking CSD with Chet Hendrickson, Ron Jeffries and Brian Levy'
    id: c47f0bee-70b0-4133-9574-9360094e366f
    type: content
  - name: What’s Eating Agile?
    id: 4d691cf9-0392-423e-9e94-bbddb1aef486
    type: content
  - name: Introducing… Matt Beam!
    id: 8f46dce0-9782-4c9c-ab06-ea139d888a08
    type: content
  - name: 'The Road to DevOps, with Jack Walser'
    id: dbbfc550-7b19-4564-95c2-1987a1a67a88
    type: content
  - name: Discussing the State of Scrum – with Maria Matarelli and Aakash Srinivasan
    id: 10f6e35b-0c20-4acc-b685-02738df1fa82
    type: content
  - name: 'Agile Training and Coaching, with Aakash Srinivasan'
    id: 4be9e3d4-7fee-45df-b1ae-5d8967adb0ad
    type: content
  - name: 'Agile Potpurri, with Vivek Angiras'
    id: 78463475-3422-4930-b2fe-b8af60e91ed8
    type: content
  - name: About Us
    id: 02f715be-8077-4f88-a828-8a939ccf2002
    type: content
  - name: '“Don’t Scrum Undone”, with Angela Johnson'
    id: 020709d8-2edc-4d47-a720-aa01d1034fbd
    type: content
  - name: Dave Sharrock – 3 Stages of Scaling Agile Organizations
    id: e45f084d-f100-4a8e-8d63-ecb14cc24ba9
    type: content
  - name: The Agile Life and Times of Mike Marchi
    id: f6c221a4-3d51-4e52-a9d6-9454d1ce9c58
    type: content
  - name: Scrum Discussion with Angela Druckman
    id: 642d26bf-cd06-4272-9315-38308516a499
    type: content
  - name: 'Agile: From Theory into Practice for Social Good'
    id: efba280f-3be0-484e-b28b-eb57a946f10b
    type: content
favicon: null
title: Agile Chicago Style Podcast
content: []
description: Helping UNLEASH the Agile Community on Chicago
purpose:
  - type: contact
    url: 'mailto:AgileChicagoStyle@gmail.com'
    label: email us!
